apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-creds
  labels:
    {{- include "skywatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.auth.erlangCookie | quote }}
